In [2]:
!pip install openpyxl

In [3]:
import pandas as pd;
import numpy as np;
import matplotlib.pyplot as plt
from sklearn import preprocessing, svm
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from math import sqrt
from math import pow

In [4]:
headers = ["temperature","voltage","out_voltage"]
data = pd.read_excel('NewData.xlsx', na_values='?',    
         header=None,names = headers) 
data = data.reset_index(drop=True)
data = data.iloc[1:] 
data= data.dropna()
data.head()
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1475 entries, 1 to 1475
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   temperature  1475 non-null   int64  
 1   voltage      1475 non-null   float64
 2   out_voltage  1475 non-null   float64
dtypes: float64(2), int64(1)
memory usage: 34.7 KB


In [5]:
data['temperature'] = pd.to_numeric(data['temperature'],errors = 'coerce')
data['voltage']= pd.to_numeric(data['voltage'],errors = 'coerce')
data['out_voltage'] = pd.to_numeric(data['out_voltage'],errors = 'coerce')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1475 entries, 1 to 1475
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   temperature  1475 non-null   int64  
 1   voltage      1475 non-null   float64
 2   out_voltage  1475 non-null   float64
dtypes: float64(2), int64(1)
memory usage: 34.7 KB


In [6]:
x = data.drop(['out_voltage'],axis=1).values
y = data['out_voltage'].values
print(x[:10])
print(y[:10])

[[26.          1.31662959]
 [27.          1.31183037]
 [28.          1.30705493]
 [29.          1.30230309]
 [30.          1.29757464]
 [31.          1.29286941]
 [32.          1.28818721]
 [33.          1.28352785]
 [34.          1.27889114]
 [35.          1.27427692]]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]


In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [8]:
print(len(x_train))
print(len(y_train))
print(len(x_test))
print(len(y_test))
print(x_train[:5])
print(x_test[:5])

1180
1180
295
295
[[28.          1.61490217]
 [60.          1.53223353]
 [37.          1.61958782]
 [51.          1.20336639]
 [60.          1.31694979]]
[[48.          1.61296835]
 [59.          1.36352867]
 [55.          1.33936159]
 [43.          1.57732523]
 [31.          1.43189203]]


In [9]:
# X = np.array(usefuldata).reshape(-1, 1);
# y = np.array(Aero_useful2).reshape(-1, 1);
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25);
regr = LinearRegression()
  
regr.fit(x_train, y_train)
predicted_outcome = regr.predict(x_test)
# print(y_test);
print(predicted_outcome[:5])
regr.coef_

[13.64679482 11.84457155 11.43786086 13.08816346 11.19373165]


array([0.04581787, 9.24560122])

In [10]:
# trying polynomial regression

from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
from sklearn.metrics import accuracy_score

poly_reg = PolynomialFeatures(degree = 2)
x_poly = poly_reg.fit_transform(x_train)
lin_reg_2=LinearRegression().fit(x_poly, y_train)
y_pred = lin_reg_2.predict(poly_reg.fit_transform(x_test)) #this line is not necessary. It's just a predict for test data
# print(pred);

lin_reg_2.coef_

array([ 0.00000000e+00, -5.89139639e-03,  4.02593665e+00,  2.65463971e-05,
        3.39135283e-02,  1.29683836e+00])

In [11]:
print(y_pred[14:24])

[13.00004784 12.7001387  13.29981933 12.49973366 10.5005279  10.30033102
 10.99949307 10.39938641 12.80015226 13.39956264]


In [12]:
print(y_test[14:24])

[13.  12.7 13.3 12.5 10.5 10.3 11.  10.4 12.8 13.4]


In [13]:
# y_pred = model.predict(x_test)

# print(y_pred*scale)
MSE=mean_squared_error(y_test, y_pred)
print("Mean squared error     :", MSE)

RMSE=sqrt(mean_squared_error(y_test, y_pred))
print("Root Mean squared error:", RMSE)

MAE=mean_absolute_error(y_test, y_pred)
print("Mean Absolute error    :", MAE)

print("R2 score    :", 100*r2_score(y_test,  y_pred))

Mean squared error     : 7.468299824515242e-07
Root Mean squared error: 0.0008641932552684753
Mean Absolute error    : 0.0006430266819208019
R2 score    : 99.99994840008509


In [14]:
input_temp = 30
input_voltage = 12
input_temp = float(input_temp)
input_voltage = float(input_voltage)
weights_linear = regr.coef_
bias_linear = regr.intercept_
# Y= bias + θ1X1 + θ2X2
weights_poly = lin_reg_2.coef_
bias_poly = lin_reg_2.intercept_
# Y= bias + θ1X1 + θ2X2
# similar to above equation do it for polynomial of degree 2
# Y= bias + θ1X1 + θ2X2 + θ3X1^2 + θ4X1X2 + θ5X2^2
# # similar to above equation do it for polynomial of degree 5
# Y= bias + θ1X1 + θ2X2 + θ3X1^2 + θ4X1X2 + θ5X2^2 + θ6X1^3 + θ7X1^2X2 + θ8X1X2^2 + θ9X2^3 + θ10X1^4 + θ11X1^3X2 + θ12X1^2X2^2 + θ13X1X2^3 + θ14X2^4 + θ15X1^5 + θ16X1^4X2 + θ17X1^3X2^2 + θ18X1^2X2^3 + θ19X1X2^4 + θ20X2^5

In [15]:
# out_voltage_poly = weights_poly[0]+weights_poly[1]*input_temp+weights_poly[2]*input_voltage+weights_poly[3]*pow(input_temp,2)+weights_poly[4]*pow(input_voltage,2)+weights_poly[5]*input_temp*input_voltage+bias_poly

# do this for degree 2
out_voltage_poly  = weights_poly[0]+weights_poly[1]*input_temp+weights_poly[2]*input_voltage+weights_poly[3]*pow(input_temp,2)+weights_poly[4]*pow(input_voltage,2)+weights_poly[5]*input_temp*input_voltage+bias_poly

# do this for degree 5
# out_voltage_poly = weights_poly[0]+weights_poly[1]*input_temp+weights_poly[2]*input_voltage+weights_poly[3]*pow(input_temp,2)+weights_poly[4]*pow(input_voltage,2)+weights_poly[5]*input_temp*input_voltage+weights_poly[6]*pow(input_temp,3)+weights_poly[7]*pow(input_temp,2)*input_voltage+weights_poly[8]*input_temp*pow(input_voltage,2)+weights_poly[9]*pow(input_voltage,3)+weights_poly[10]*pow(input_temp,4)+weights_poly[11]*pow(input_temp,3)*input_voltage+weights_poly[12]*pow(input_temp,2)*pow(input_voltage,2)+weights_poly[13]*input_temp*pow(input_voltage,3)+weights_poly[14]*pow(input_voltage,4)+weights_poly[15]*pow(input_temp,5)+weights_poly[16]*pow(input_temp,4)*input_voltage+weights_poly[17]*pow(input_temp,3)*pow(input_voltage,2)+weights_poly[18]*pow(input_temp,2)*pow(input_voltage,3)+weights_poly[19]*input_temp*pow(input_voltage,4)+weights_poly[20]*pow(input_voltage,5)+bias_poly

out_voltage_linear = weights_linear[0]*input_temp+weights_linear[1]*input_voltage+bias_linear
print("out_voltage_poly: ",out_voltage_poly)
print("out_voltage_linear: ",out_voltage_linear)

out_voltage_poly:  521.3309863769377
out_voltage_linear:  108.85642572811071


In [16]:
weights = regr.coef_
bias = regr.intercept_
print("weights and bias with linear regression")
print("weights: ",weights)
print("bias: ",bias)

weights = lin_reg_2.coef_
bias = lin_reg_2.intercept_
print("weights and bias with polynomial regression")
print("weights: ",weights)
print("bias: ",bias)
# Y= θ0+θ1X1+θ2X2 +θ3X1^2+θ4X2^2+θ5X1X2

weights and bias with linear regression
weights:  [0.04581787 9.24560122]
bias:  -3.4653249227461185
weights and bias with polynomial regression
weights:  [ 0.00000000e+00 -5.89139639e-03  4.02593665e+00  2.65463971e-05
  3.39135283e-02  1.29683836e+00]
bias:  1.4272408716245053
